### PR TITLE
docs(readme): Added potential issue with addon

### PR DESCRIPTION
**Pull request by ash-grennan**

### CODE REVIEW

**Comment by cannonpalms** [comment]
Thanks for the PR. Can you describe to me the interaction between the open @ mouse setting and looting speed? I’m happy to merge this once I either understand from you what is happening, or have a chance to test it myself after launch.

**Comment by ash-grennan** [comment]
No problem, I don't have anything concrete to base this other than my own experience. When the 'Open Loot Window at Mouse' option is checked, it seems the standard looting time returns, when I disable, looting appear to be faster, due to your addon. Perhaps it was something else, I'll try re-create if you'd like?

**Comment by cannonpalms** [comment]
I do appreciate your contribution, especially to an area such as documentation where the project is sorely lacking. However, I am hesitant to merge your PR without confirming definitively that "Open loot window at mouse" is causing slowness. Looting times vary so drastically simply due to server lag that I am inclined to believe that perhaps what you experienced was coincidental lag.

If you can record data that shows evidence of this setting slowing down looting, I will happily merge.  Until then, however, I'd like to avoid spreading this kind of information.

Cannon

**Comment by cannonpalms** [comment]
Release version 1.1.0 adds explicit support for the “show under cursor” setting, although it may not have been needed. 

To be perfectly clear, this setting does not affect the speed of looting under any circumstances—without this addon or with any version of this addon.

**Pull request closed without merging**
